name: star_movie
description: "Online database of information related to films"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  flutter_dotenv: ^5.2.1
  dio: ^5.7.0
  shared_preferences: ^2.3.3
  get_it: ^8.0.3
  collection: ^1.18.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
